<?php

/**
 * @file
 * website.module
 *
 * Website theme override hooks.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function website_page_attachments_alter(array &$page) {
  $meta_data = array(
    'HandheldFriendly',
    'MobileOptimized',
    'system_meta_generator',
  );

  foreach ($page['#attached']['html_head'] as $key => $value) {
    if (in_array($value[1], $meta_data)) {
      unset($page['#attached']['html_head'][$key]);
    }
  }
}

/**
 * Implements hook_theme().
 */
function website_theme($existing, $type, $theme, $path) {
  $template_dir = drupal_get_path('module', 'website') . '/templates';

  $themes = array();

  $themes['website_content'] = array(
    'template' => 'content',
    'variables' => array(
      'node' => NULL,
    ),
    'path' => $template_dir . '/node',
  );

  return $themes;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function website_preprocess_html(&$variables) {
  $site_config = \Drupal::config('system.site');

  if (\Drupal::currentUser()->isAnonymous()) {
    $head_title = array(
      'name' => $site_config->get('name'),
      'title' => $site_config->get('slogan'),
    );

    $variables['head_title'] = $head_title;

    $meta_tags = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'description',
        'content' => '',
      ),
    );

    $variables['page']['#attached']['html_head'][] = [$meta_tags, 'description'];
  }
}
